### ISSUE TITLE
Detalhar melhor o README do projeto

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/atomoids#1]
Escrever detalhes do projeto, como:

1. Qual o objetivo do projeto?
2. Qual a motivação em desenvolver este projeto?
  - Deverá ter qual a motivação por trás de desenvolver este jogo
  - A importância do tema (na área de química) do que se trata este jogo.
3. A quem se destina este projeto (as personas)?
4. Quais as ferramentas e tecnologias que serão utilizadas neste projeto?
5. Quais os outros trabalhos existentes relacionados a este projeto (se houver)?

Não esqueçam que o README deverá estar no formato Markdown.

**Comment by fabriciofx** [comment]
@AdonisBelo e @Danielgol,

incluir também os tópico **Motivação**, no qual deverá ter qual a motivação por trás de desenvolver este jogo, bem como a importância do tema (na área de química) do que se trata este jogo.

Não esqueçam que o README deverá estar no formato Markdown.

**Comment by AdonisBelo** [comment]
Professor, eu detalhei melhor o readme, gostaria que o senhor desse uma olhada nele antes de fechar essa issue.

**Comment by fabriciofx** [comment]
@AdonisBelo 

Ficou bom! Mas dê uma olhada no issue #7 também, ok?
