### ISSUE TITLE
Estudar o formato Markdown

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/atomoids#4]
@AdonisBelo e @Danielgol favor estudar o formato Markdown. Algumas referências:

[Referência 1](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
[Referência 2](https://daringfireball.net/projects/markdown/syntax)

Mais informações, consulte o [Google](https://www.google.com)

**Comment by AdonisBelo** [comment]
Professor, eu dei uma boa lida nessas páginas que o senhor nos mandou e aprendi a utilizar o formato markdown da maneira correta.

**Comment by fabriciofx** [comment]
@AdonisBelo 

Ler é uma coisa, entender e utilizar é outra. Vou fechar a issue, mas vou confiar, hein? Se não utilizar o Markdown corretamente, vou voltar a abrir, ok?
