### ISSUE TITLE
Aprender a utilizar java junto com javascript

### ISSUE THREAD

**Issue by Danielgol** [ifpe-cti/atomoids#6]
Precisamos aprender como fazer o javascript reconhecer os valores das variáveis java,
deixando o papel de realizar as ações em java e depois enviar para o javascript e assim "imprimir" no canvas.

@fabriciofx 
Como podemos fazer isso?

**Comment by fabriciofx** [comment]
@Danielgol 

Acho que você está confundindo um pouco as coisas. Tem que entender como funciona a web (protocolo http e arquitetura cliente-servidor). O código Java é seu lado servidor; o código JavaScript é o seu código cliente. Se você quer pegar alguma informação do lado servidor e enviar para o lado cliente, precisa fazer um response para o cliente e este, na mensagem de response, vai pegar a informação que precisa e utilizar no código JavaScript. Mesma coisa acontece no lado cliente: se este precisa enviar uma informação para o lado servidor, deverá fazer um request com as infomações. Por sua vez, o servidor irá pegar este request e separar as informações que precisa.

Então o que você precisa agora é pesquisar como fazer o seu código JavaScript enviar e receber requisições de um servidor web.

**Comment by Danielgol** [comment]
Usaremos javascript
